export const applicants = [
    {
      name: "John Doe",
      status: "Applied",
      course: "BSIT",
      progress: "100",
      source: "LinkedIn",
    },
    {
      name: "Jane Smith",
      status: "Interview Scheduled",
      course: "BSCpE",
      progress: "80",
      source: "Indeed",
    },
    {
      name: "Michael Johnson",
      status: "Screening",
      course: "BSCS",
      progress: "60",
      source: "JobStreet",
    },
    {
      name: "Emily Davis",
      status: "Applied",
      course: "BSIS",
      progress: "100",
      source: "Company Website",
    },
    {
      name: "David Martinez",
      status: "Hired",
      course: "BSIT",
      progress: "100",
      source: "Referral",
    },
    {
      name: "Sarah Brown",
      status: "Rejected",
      course: "BSCS",
      progress: "30",
      source: "LinkedIn",
    },
    {
      name: "Robert Wilson",
      status: "Offer Extended",
      course: "BSCpE",
      progress: "95",
      source: "Indeed",
    },
    {
      name: "Jessica Taylor",
      status: "Interview Scheduled",
      course: "BSIT",
      progress: "80",
      source: "Facebook Jobs",
    },
    {
      name: "William Anderson",
      status: "Screening",
      course: "BSIS",
      progress: "55",
      source: "JobStreet",
    },
    {
      name: "Olivia Thomas",
      status: "Applied",
      course: "BSCS",
      progress: "100",
      source: "Glassdoor",
    },
    {
      name: "James White",
      status: "Hired",
      course: "BSIT",
      progress: "100",
      source: "Referral",
    },
    {
      name: "John Doe",
      status: "Applied",
      course: "BSIT",
      progress: "100",
      source: "LinkedIn",
    },
    {
      name: "Jane Smith",
      status: "Interview Scheduled",
      course: "BSCpE",
      progress: "80",
      source: "Indeed",
    },
    {
      name: "Michael Johnson",
      status: "Screening",
      course: "BSCS",
      progress: "60",
      source: "JobStreet",
    },
    {
      name: "Jane Smith",
      status: "Interview Scheduled",
      course: "BSCpE",
      progress: "80",
      source: "Indeed",
    },
    {
      name: "Michael Johnson",
      status: "Screening",
      course: "BSCS",
      progress: "60",
      source: "JobStreet",
    },
    {
      name: "Jane Smith",
      status: "Interview Scheduled",
      course: "BSCpE",
      progress: "80",
      source: "Indeed",
    },
    {
      name: "Michael Johnson",
      status: "Screening",
      course: "BSCS",
      progress: "60",
      source: "JobStreet",
    },
    {
      name: "Emily Davis",
      status: "Applied",
      course: "BSIS",
      progress: "100",
      source: "Company Website",
    },
    {
      name: "David Martinez",
      status: "Hired",
      course: "BSIT",
      progress: "100",
      source: "Referral",
    },
  ];