export const feedbacks = [
  {
    id: 1,
    user: "John Doe",
    feedback: "Great service!",
    rating: "5/5",
    date: "2024-02-02",
  },
  {
    id: 2,
    user: "Jane Smith",
    feedback: "Could be improved.",
    rating: "3/5",
    date: "2024-02-01",
  },
  {
    id: 3,
    user: "Alice Johnson",
    feedback: "Excellent experience!",
    rating: "5/5",
    date: "2024-01-30",
  },
  {
    id: 4,
    user: "Michael Brown",
    feedback: "Very professional.",
    rating: "4/5",
    date: "2024-01-29",
  },
  {
    id: 5,
    user: "Sarah Wilson",
    feedback: "Loved the service!",
    rating: "5/5",
    date: "2024-01-28",
  },
  {
    id: 6,
    user: "David Lee",
    feedback: "It was okay.",
    rating: "3/5",
    date: "2024-01-27",
  },
  {
    id: 7,
    user: "Emily Davis",
    feedback: "Highly recommend!",
    rating: "5/5",
    date: "2024-01-26",
  },
  {
    id: 8,
    user: "James Taylor",
    feedback: "Not satisfied.",
    rating: "2/5",
    date: "2024-01-25",
  },
  {
    id: 9,
    user: "Olivia Martinez",
    feedback: "Very polite staff.",
    rating: "4/5",
    date: "2024-01-24",
  },
  {
    id: 10,
    user: "Daniel Anderson",
    feedback: "Fast response time.",
    rating: "5/5",
    date: "2024-01-23",
  },
  {
    id: 11,
    user: "Sophia Thomas",
    feedback: "Good experience overall.",
    rating: "4/5",
    date: "2024-01-22",
  },
  {
    id: 12,
    user: "Matthew White",
    feedback: "Could be better.",
    rating: "3/5",
    date: "2024-01-21",
  },
  {
    id: 13,
    user: "Charlotte Harris",
    feedback: "Absolutely loved it!",
    rating: "5/5",
    date: "2024-01-20",
  },
  {
    id: 14,
    user: "Liam Clark",
    feedback: "Service was decent.",
    rating: "3/5",
    date: "2024-01-19",
  },
  {
    id: 15,
    user: "Amelia Lewis",
    feedback: "Friendly staff.",
    rating: "4/5",
    date: "2024-01-18",
  },
  {
    id: 16,
    user: "Benjamin Walker",
    feedback: "Highly recommend!",
    rating: "5/5",
    date: "2024-01-17",
  },
  {
    id: 17,
    user: "Mia Hall",
    feedback: "Would visit again.",
    rating: "4/5",
    date: "2024-01-16",
  },
  {
    id: 18,
    user: "Ethan Allen",
    feedback: "Not up to the mark.",
    rating: "2/5",
    date: "2024-01-15",
  },
  {
    id: 19,
    user: "Harper Young",
    feedback: "Amazing customer support!",
    rating: "5/5",
    date: "2024-01-14",
  },
  {
    id: 20,
    user: "Alexander King",
    feedback: "Decent but needs improvement.",
    rating: "3/5",
    date: "2024-01-13",
  },
  {
    id: 21,
    user: "Isabella Wright",
    feedback: "Fantastic experience!",
    rating: "5/5",
    date: "2024-01-12",
  },
  {
    id: 22,
    user: "William Scott",
    feedback: "Could use better communication.",
    rating: "3/5",
    date: "2024-01-11",
  },
  {
    id: 23,
    user: "Emma Green",
    feedback: "Very satisfied!",
    rating: "5/5",
    date: "2024-01-10",
  },
];
